spring:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: a123456
    connectionTestQuery: select 1
    maximumPoolSize: 5
  jpa:
    show-sql: true

logging:
  level:
    ROOT: 'INFO'
    ru.project: 'DEBUG'
#    org.hibernate.type: 'TRACE'

management:
  port: 8080

server:
  port: 8080